### ISSUE TITLE
Adding Event Listeners to Map

### ISSUE THREAD

**Issue by augsismyburger** [nss-day-cohort-19/d19-group-theme-park-weregoingtoflorida-1#61]
Given: User is on index page

When: User clicks on specific park area

Then: Event listeners are connected to map and Park area specific filters are displayed.

**Comment by chazhenricks** [comment]
Add event listeners to each of the area sections of the main map on home page

**Comment by chazhenricks** [comment]
RYAN DID IT. 
I WATCHED HIM DO IT.
